package com.example.moviecatalogue.repository

import com.example.moviecatalogue.R
import com.example.moviecatalogue.model.ContentEntity

object DataDummy {
    fun generateDummyContentMovies(): List<ContentEntity> {
        val content = ArrayList<ContentEntity>()
        content.add(ContentEntity("1","A Star Is Born","Drama, Romance, Music", 7.5, "Seasoned musician Jackson Maine discovers — and falls in love with — struggling artist Ally. She has just about given up on her dream to make it big as a singer — until Jack coaxes her into the spotlight. But even as Ally's career takes off, the personal side of their relationship is breaking down, as Jack fights an ongoing battle with his own internal demons.", R.drawable.poster_a_start_is_born))
        content.add(ContentEntity("2","Alita","Action, Science Fiction, Adventure", 7.2, "When Alita awakens with no memory of who she is in a future world she does not recognize, she is taken in by Ido, a compassionate doctor who realizes that somewhere in this abandoned cyborg shell is the heart and soul of a young woman with an extraordinary past.", R.drawable.poster_alita))
        content.add(ContentEntity("3","Aquaman","Action, Adventure, Fantasy", 6.9, "Once home to the most advanced civilization on Earth, Atlantis is now an underwater kingdom ruled by the power-hungry King Orm. With a vast army at his disposal, Orm plans to conquer the remaining oceanic people and then the surface world. Standing in his way is Arthur Curry, Orm's half-human, half-Atlantean brother and true heir to the throne.", R.drawable.poster_aquaman))
        content.add(ContentEntity("4","Bohemian Rhapsody","Music, Drama, History", 8.0, "Singer Freddie Mercury, guitarist Brian May, drummer Roger Taylor and bass guitarist John Deacon take the music world by storm when they form the rock 'n' roll band Queen in 1970. Hit songs become instant classics. When Mercury's increasingly wild lifestyle starts to spiral out of control, Queen soon faces its greatest challenge yet – finding a way to keep the band together amid the success and excess.", R.drawable.poster_bohemian))
        content.add(ContentEntity("5","Cold Pursuit","Action, Crime, Thriller", 5.7, "The quiet family life of Nels Coxman, a snowplow driver, is upended after his son's murder. Nels begins a vengeful hunt for Viking, the drug lord he holds responsible for the killing, eliminating Viking's associates one by one. As Nels draws closer to Viking, his actions bring even more unexpected and violent consequences, as he proves that revenge is all in the execution.", R.drawable.poster_cold_persuit))
        content.add(ContentEntity("6","Creed","Drama", 6.9, "Between personal obligations and training for his next big fight against an opponent with ties to his family's past, Adonis Creed is up against the challenge of his life.", R.drawable.poster_creed))
        content.add(ContentEntity("7","Crimes Grindelwald","Adventure, Fantasy, Drama", 6.9, "Gellert Grindelwald has escaped imprisonment and has begun gathering followers to his cause—elevating wizards above all non-magical beings. The only one capable of putting a stop to him is the wizard he once called his closest friend, Albus Dumbledore. However, Dumbledore will need to seek help from the wizard who had thwarted Grindelwald once before, his former student Newt Scamander, who agrees to help, unaware of the dangers that lie ahead. Lines are drawn as love and loyalty are tested, even among the truest friends and family, in an increasingly divided wizarding world.", R.drawable.poster_crimes))
        content.add(ContentEntity("8","Glass","Thriller, Drama, Science Fiction", 6.7, "In a series of escalating encounters, former security guard David Dunn uses his supernatural abilities to track Kevin Wendell Crumb, a disturbed man who has twenty-four personalities. Meanwhile, the shadowy presence of Elijah Price emerges as an orchestrator who holds secrets critical to both men.", R.drawable.poster_glass))
        content.add(ContentEntity("9","How To Train Your Dragon","Animation, Family, Adventure", 7.8, "As Hiccup fulfills his dream of creating a peaceful dragon utopia, Toothless’ discovery of an untamed, elusive mate draws the Night Fury away. When danger mounts at home and Hiccup’s reign as village chief is tested, both dragon and rider must make impossible decisions to save their kind.", R.drawable.poster_how_to_train))
        content.add(ContentEntity("10","Avenger Infinity War","Adventure, Action, Science Fiction", 8.3, "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.", R.drawable.poster_infinity_war))
        content.add(ContentEntity("11","Mary Queen","Drama, History", 6.6, "In 1561, Mary Stuart, widow of the King of France, returns to Scotland, reclaims her rightful throne and menaces the future of Queen Elizabeth I as ruler of England, because she has a legitimate claim to the English throne. Betrayals, rebellions, conspiracies and their own life choices imperil both Queens. They experience the bitter cost of power, until their tragic fate is finally fulfilled.", R.drawable.poster_marry_queen))
        content.add(ContentEntity("12","Master Z","Action", 6.0, "Following his defeat by Master Ip, Cheung Tin Chi tries to make a life with his young son in Hong Kong, waiting tables at a bar that caters to expats. But it's not long before the mix of foreigners, money, and triad leaders draw him once again to the fight.", R.drawable.poster_master_z))
        content.add(ContentEntity("13","Mortal Engines","Adventure, Science Fiction", 6.1, "Many thousands of years in the future, Earth’s cities roam the globe on huge wheels, devouring each other in a struggle for ever diminishing resources. On one of these massive traction cities, the old London, Tom Natsworthy has an unexpected encounter with a mysterious young woman from the wastelands who will change the course of his life forever.", R.drawable.poster_mortal_engines))
        content.add(ContentEntity("14","Overlord","Horror, War, Science Fiction", 6.7, "France, June 1944. On the eve of D-Day, some American paratroopers fall behind enemy lines after their aircraft crashes while on a mission to destroy a radio tower in a small village near the beaches of Normandy. After reaching their target, the surviving paratroopers realise that, in addition to fighting the Nazi troops that patrol the village, they also must fight against something else.", R.drawable.poster_overlord))
        content.add(ContentEntity("15","Ralph","Family, Animation, Comedy, Adventure", 7.2, "Video game bad guy Ralph and fellow misfit Vanellope von Schweetz must risk it all by traveling to the World Wide Web in search of a replacement part to save Vanellope's video game, Sugar Rush. In way over their heads, Ralph and Vanellope rely on the citizens of the internet — the netizens — to help navigate their way, including an entrepreneur named Yesss, who is the head algorithm and the heart and soul of trend-making site BuzzzTube.", R.drawable.poster_ralph))
        content.add(ContentEntity("16","Robin Hood","Adventure, Action, Thriller", 5.9, "A war-hardened Crusader and his Moorish commander mount an audacious revolt against the corrupt English crown.", R.drawable.poster_robin_hood))
        content.add(ContentEntity("17","Serenity","Thriller, Mystery, Drama", 5.4, "The quiet life of Baker Dill, a fishing boat captain who lives on the isolated Plymouth Island, where he spends his days obsessed with capturing an elusive tuna while fighting his personal demons, is interrupted when someone from his past comes to him searching for help.", R.drawable.poster_serenity))
        content.add(ContentEntity("18","Spiderman","Action, Adventure, Science Fiction, Drama", 7.4, "Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.", R.drawable.poster_spiderman))
        content.add(ContentEntity("19","T-34","War, Action, Drama, History", 6.9, "In 1944, a courageous group of Russian soldiers managed to escape from German captivity in a half-destroyed legendary T-34 tank. Those were the times of unforgettable bravery, fierce fighting, unbreakable love, and legendary miracles.", R.drawable.poster_t34))
        return content
    }

    fun generateDummyContentShow(): List<ContentEntity> {
        val content = ArrayList<ContentEntity>()
        content.add(ContentEntity("1","Arrow","Crime, Drama, Mystery, Action & Adventure", 6.6, "Spoiled billionaire playboy Oliver Queen is missing and presumed dead when his yacht is lost at sea. He returns five years later a changed man, determined to clean up the city as a hooded vigilante armed with a bow.", R.drawable.poster_arrow))
        content.add(ContentEntity("2","Doom Patrol","Sci-Fi & Fantasy, Comedy, Drama", 7.6, "The Doom Patrol’s members each suffered horrible accidents that gave them superhuman abilities — but also left them scarred and disfigured. Traumatized and downtrodden, the team found purpose through The Chief, who brought them together to investigate the weirdest phenomena in existence — and to protect Earth from what they find.", R.drawable.poster_doom_patrol))
        content.add(ContentEntity("3","Dragon Ball","Animation, Sci-Fi & Fantasy, Action & Adventure", 8.2, "Five years have passed since the fight with Piccolo Jr., and Goku now has a son, Gohan. The peace is interrupted when an alien named Raditz arrives on Earth in a spacecraft and tracks down Goku, revealing to him that that they are members of a near-extinct warrior race called the Saiyans.", R.drawable.poster_dragon_ball))
        content.add(ContentEntity("4","Fairy Tail","Action, Animation, Comedy, Sci-Fi & Fantasy, Mystery", 7.8, "Lucy is a 17-year-old girl, who wants to be a full-fledged mage. One day when visiting Harujion Town, she meets Natsu, a young man who gets sick easily by any type of transportation. But Natsu isn't just any ordinary kid, he's a member of one of the world's most infamous mage guilds: Fairy Tail.", R.drawable.poster_fairytail))
        content.add(ContentEntity("5","Family Guy","Animation, Fantasy, Comedy, Science Fiction, Adventure", 6.8, "With the Griffins stuck again at home during a blackout, Peter tells the story of 'Star Wars Episode VI: Return of the Jedi.'", R.drawable.poster_family_guy))
        content.add(ContentEntity("6","The Flash","Drama, Sci-Fi & Fantasy", 7.7, "After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only \"meta-human\" who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent.", R.drawable.poster_flash))
        content.add(ContentEntity("7","Gotham","Drama, Crime, Sci-Fi & Fantasy", 7.5, "Everyone knows the name Commissioner Gordon. He is one of the crime world's greatest foes, a man whose reputation is synonymous with law and order. But what is known of Gordon's story and his rise from rookie detective to Police Commissioner? What did it take to navigate the multiple layers of corruption that secretly ruled Gotham City, the spawning ground of the world's most iconic villains? And what circumstances created them – the larger-than-life personas who would become Catwoman, The Penguin, The Riddler, Two-Face and The Joker?", R.drawable.poster_gotham))
        content.add(ContentEntity("8","Grey Anatomy","Drama", 8.2, "Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.", R.drawable.poster_grey_anatomy))
        content.add(ContentEntity("9","Hanna","Action & Adventure, Drama", 7.5, "This thriller and coming-of-age drama follows the journey of an extraordinary young girl as she evades the relentless pursuit of an off-book CIA agent and tries to unearth the truth behind who she is. Based on the 2011 Joe Wright film.", R.drawable.poster_hanna))
        content.add(ContentEntity("10","Iron Fist","Action & Adventure, Drama, Sci-Fi & Fantasy", 6.6, "Danny Rand resurfaces 15 years after being presumed dead. Now, with the power of the Iron Fist, he seeks to reclaim his past and fulfill his destiny.", R.drawable.poster_iron_fist))
        content.add(ContentEntity("11","Naruto Shippuden","Animation, Action & Adventure, Sci-Fi & Fantasy", 8.6, "Naruto Shippuuden is the continuation of the original animated TV series Naruto.The story revolves around an older and slightly more matured Uzumaki Naruto and his quest to save his friend Uchiha Sasuke from the grips of the snake-like Shinobi, Orochimaru. After 2 and a half years Naruto finally returns to his village of Konoha, and sets about putting his ambitions to work, though it will not be easy, as He has amassed a few (more dangerous) enemies, in the likes of the shinobi organization; Akatsuki.", R.drawable.poster_naruto_shipudden))
        content.add(ContentEntity("12","NCIS","Crime, Action & Adventure, Drama", 7.4, "From murder and espionage to terrorism and stolen submarines, a team of special agents investigates any crime that has a shred of evidence connected to Navy and Marine Corps personnel, regardless of rank or position.", R.drawable.poster_ncis))
        content.add(ContentEntity("13","Riverdale","Mystery, Drama, Crime", 8.6, "Set in the present, the series offers a bold, subversive take on Archie, Betty, Veronica and their friends, exploring the surreality of small-town life, the darkness and weirdness bubbling beneath Riverdale’s wholesome facade.", R.drawable.poster_riverdale))
        content.add(ContentEntity("14","Shameless","Drama, Comedy", 8.0, "Chicagoan Frank Gallagher is the proud single dad of six smart, industrious, independent kids, who without him would be... perhaps better off. When Frank's not at the bar spending what little money they have, he's passed out on the floor. But the kids have found ways to grow up in spite of him. They may not be like any family you know, but they make no apologies for being exactly who they are.", R.drawable.poster_shameless))
        content.add(ContentEntity("15","Supergirl","Drama, Sci-Fi & Fantasy, Action & Adventure", 7.3, "Twenty-four-year-old Kara Zor-El, who was taken in by the Danvers family when she was 13 after being sent away from Krypton, must learn to embrace her powers after previously hiding them. The Danvers teach her to be careful with her powers, until she has to reveal them during an unexpected disaster, setting her on her journey of heroism.", R.drawable.poster_supergirl))
        content.add(ContentEntity("16","Supernatural","Drama, Mystery, Sci-Fi & Fantasy", 8.2, "When they were boys, Sam and Dean Winchester lost their mother to a mysterious and demonic supernatural force. Subsequently, their father raised them to be soldiers. He taught them about the paranormal evil that lives in the dark corners and on the back roads of America ... and he taught them how to kill it. Now, the Winchester brothers crisscross the country in their '67 Chevy Impala, battling every kind of supernatural threat they encounter along the way.", R.drawable.poster_supernatural))
        content.add(ContentEntity("17","The Simpsons","Family, Animation, Comedy", 7.8, "Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.", R.drawable.poster_the_simpson))
        content.add(ContentEntity("18","The Umbrella","Action & Adventure, Sci-Fi & Fantasy, Drama", 8.7, "A dysfunctional family of superheroes comes together to solve the mystery of their father's death, the threat of the apocalypse and more.", R.drawable.poster_the_umbrella))
        content.add(ContentEntity("19","The Walking Dead","Action & Adventure, Drama, Sci-Fi & Fantasy", 8.1, "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.", R.drawable.poster_the_walking_dead))
        return content
    }
}